name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
    types: [opened, synchronize, reopened]

jobs:
  project-build-test:
    uses: asimov-platform/.github/.github/workflows/npm-ci.yml@master
    with:
      skip-tests: true
